### ISSUE TITLE
Почта обратной связи

### ISSUE THREAD

**Issue by SLywnow** [optozorax/unasanu#1]
Не знаю баг или фича, но почта обратной связи оставлена так, что какие комбинпции не пробуй - гмайл не видит.

Ну и как насчет телеги, дискорда или своего мини-форума. Статья жутко интересная, я лично покажу ее профессорам, в т.ч по философии, так что может быть даже получишь ответ от людей со степенью, если заинтересуются.
Отличная работа!

**Comment by optozorax** [comment]
Привет, спасибо за фидбэк! Почту специально написал чтобы автоматически не парсили, но видимо не очень понятно. Тогда добавлю телеграм-чат: `@unasanu`

**Comment by optozorax** [comment]
Обновил информацию в статье: https://github.com/optozorax/unasanu/commit/05e18223079ec40b136e2bc0818c840e66ad9f2f
